import type { Metadata } from "next";
import Script from "next/script";
import FaqsPageClient from "@/components/sections/faqs/FaqsPageClient";

export const metadata: Metadata = {
  title:       "PrintOpsAI FAQs — Print Shop AI Automation Answered",
  description: "Answers to every question about PrintOpsAI's AI chatbot, web-to-print, workflow automation, DevOps, and custom AI for print shops. USA & Canada.",
  alternates:  { canonical: "https://printai.cloud/faqs" },
  openGraph: {
    title:       "PrintOpsAI FAQs — Print Shop AI Automation Answered",
    description: "Answers to every question about PrintOpsAI's AI chatbot, web-to-print, workflow automation, DevOps, and custom AI for print shops. USA & Canada.",
    url:         "https://printai.cloud/faqs",
    siteName:    "PrintOpsAI",
    type:        "website",
  },
};

const faqSchema = {
  "@context":   "https://schema.org",
  "@type":      "FAQPage",
  mainEntity: [
    /* ── About PrintOpsAI ─────────────────────────────────── */
    { "@type": "Question", name: "What is PrintOpsAI?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI is an AI automation platform built exclusively for print businesses. We build AI-powered tools that help print shops automate customer quoting, online ordering, workflow automation from order intake to shipping, custom AI development, and managed DevOps infrastructure. We serve commercial printers, web-to-print businesses, multi-location print chains, packaging printers, and in-plant operations across the USA and Canada." } },
    { "@type": "Question", name: "Who is PrintOpsAI built for?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI is built for print businesses in the USA and Canada that want to grow without adding headcount — specifically commercial print shops (10–200 staff), web-to-print businesses, multi-location print chains, packaging and large-format printers, and in-plant print operations. If your print business is running on spreadsheets, disconnected tools, and manual quoting, PrintOpsAI was built for you." } },
    { "@type": "Question", name: "Is PrintOpsAI based in the USA?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI is a USA and Canada-focused company with team members and operations across North America. All client accounts are managed by US-based account leads. Support operates in US and Canadian timezones. We serve print businesses across all major US markets and throughout Canada." } },
    { "@type": "Question", name: "How is PrintOpsAI different from OnPrintShop, Printavo, or other print software?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI is a complete AI automation platform — not a single-function tool. vs OnPrintShop: OnPrintShop is a web-to-print storefront; PrintOpsAI includes web-to-print AND an AI chatbot, workflow automation, DevOps, and custom AI. vs Printavo: Printavo is focused on screen printing and apparel; PrintOpsAI serves commercial, digital, web-to-print, packaging, and large-format. vs generic AI tools: tools like Tidio or Intercom have no print-specific knowledge — PrintOpsAI's AI is trained on print operations." } },
    { "@type": "Question", name: "Does PrintOpsAI replace my existing software or work alongside it?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI is designed to work alongside your existing tools — not replace them all at once. If you run a print MIS, Shopify store, QuickBooks, and CRM, PrintOpsAI connects to all of them and adds AI automation on top without requiring you to switch platforms. The only exception: the web-to-print platform replaces your existing web store with a Shopify or WooCommerce store configured for print." } },
    { "@type": "Question", name: "What types of print businesses does PrintOpsAI NOT serve?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI does not serve print-on-demand businesses like Printful or Printify resellers, consumer photo print companies, or apparel screen printing shops. Our platform is built for commercial print operations — businesses that print on paper, board, substrate, or packaging for business clients. We also don't currently serve newspaper publishers, book printers, or 3D printing businesses." } },
    { "@type": "Question", name: "How long has PrintOpsAI been operating?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI was built by a team with over 20 years of combined experience in print technology, AI development, and print operations consulting across the USA and Canada. We have onboarded 250+ print businesses across North America, with case studies showing $120K+ average annual savings, 300% revenue growth from web-to-print deployment, and 80%+ auto-resolution of customer enquiries via AI chatbot." } },
    /* ── AI Chatbot ────────────────────────────────────────── */
    { "@type": "Question", name: "What is an AI chatbot for a print shop?", acceptedAnswer: { "@type": "Answer", text: "An AI chatbot for a print shop is a software system trained on your shop's specific pricing, products, turnaround times, and file specifications that answers customer enquiries automatically, 24 hours a day. Unlike generic chatbots, a print-specific AI chatbot gives accurate price quotes, explains your exact file spec requirements, checks your current capacity rules, and routes complex jobs to your team with full order context. PrintOpsAI's AI chatbot is trained specifically on your shop's data — not a generic print industry template." } },
    { "@type": "Question", name: "How accurate is the AI chatbot at quoting print jobs?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI's AI chatbot quotes from your exact price book — not a generic estimate. Our clients consistently report that chatbot-generated quotes match human-generated quotes at 97%+ accuracy. The 3% variance comes from complex or out-of-catalogue jobs that the chatbot correctly flags for human review. Price changes are reflected in the chatbot within 24 hours of you updating your price book." } },
    { "@type": "Question", name: "How long does it take to set up a print shop AI chatbot?", acceptedAnswer: { "@type": "Answer", text: "Most PrintOpsAI clients have a live, trained AI chatbot on their website within 48–72 hours. You provide your current price book, product catalogue, standard turnaround times, and FAQs your team answers manually. We handle all AI training, testing, deployment, and QA. No code is required on your side and there is no disruption to your existing website." } },
    { "@type": "Question", name: "Can the chatbot handle after-hours enquiries and leads?", acceptedAnswer: { "@type": "Answer", text: "Yes — capturing after-hours leads is the primary reason most print shops deploy an AI chatbot. Over 60% of print shop enquiries arrive outside business hours. PrintOpsAI's AI chatbot responds within seconds, 24/7 — giving accurate quotes, answering file spec questions, capturing contact details, and routing complex jobs to your team. Our clients typically see a 38% increase in after-hours leads captured within the first 30 days." } },
    { "@type": "Question", name: "Which channels can the print chatbot be deployed on?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI's AI chatbot can be deployed simultaneously on your website, WhatsApp Business, and email. All channels are managed from one dashboard. Training your chatbot once covers all channels — you don't need to create separate versions for each platform. Multi-channel deployment is included in all PrintOpsAI AI Chatbot plans at no extra cost." } },
    { "@type": "Question", name: "Will the AI chatbot replace my customer service team?", acceptedAnswer: { "@type": "Answer", text: "No — PrintOpsAI's AI chatbot is designed to handle the repetitive 80% so your team focuses on the valuable 20%. The chatbot handles standard pricing questions, turnaround times, file spec requirements, and order status automatically. Your team is freed to focus on large custom jobs, enterprise relationships, and complex technical conversations. Clients consistently report their teams are less stressed and more productive within 30 days." } },
    /* ── Web-to-Print ──────────────────────────────────────── */
    { "@type": "Question", name: "What is web-to-print software?", acceptedAnswer: { "@type": "Answer", text: "Web-to-print software is a platform that lets customers configure, price, and order printed products online without calling your team for a quote or file guidance. A web-to-print store lets customers select a product, choose specifications, see the price update live, upload artwork, pass automated file preflight, and pay — all without manual involvement from your team. PrintOpsAI builds web-to-print stores on Shopify or WooCommerce. You own your store, your data, and your customer list permanently." } },
    { "@type": "Question", name: "What platforms does PrintOpsAI build web-to-print stores on?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI builds web-to-print stores on Shopify or WooCommerce — your choice based on your business model. Shopify is recommended for shops wanting a fast-to-launch platform with strong mobile performance, ideal for B2C and simple B2B. WooCommerce is better for shops needing deeper customisation, complex B2B pricing logic, or who already run WordPress. Both give you complete ownership of your store — you are never locked into a proprietary system." } },
    { "@type": "Question", name: "How long does it take to launch a web-to-print store?", acceptedAnswer: { "@type": "Answer", text: "Most PrintOpsAI web-to-print stores are live within 2–3 weeks of project kick-off. Week 1: platform setup, product catalogue, pricing matrix. Week 2: B2B portal, preflight rules, payment and shipping integration, testing. Week 3: client review, adjustments, staff training, go-live. For simpler stores, launch can happen in 7–10 days. For complex stores with 50+ products and multiple B2B tiers, 3–4 weeks. No developer knowledge required on your side." } },
    { "@type": "Question", name: "Can the web-to-print store handle B2B accounts and corporate portals?", acceptedAnswer: { "@type": "Answer", text: "Yes — B2B account management is one of the core capabilities of PrintOpsAI's web-to-print platform. Each B2B account gets a login-protected portal with contracted pricing, approved brand templates with locked parameters, order history with one-click reorder, and their own shipping and billing details. For franchise networks, head office controls brand templates and individual locations order through their own portals but cannot change brand assets." } },
    { "@type": "Question", name: "Does the web-to-print store include automated file preflight?", acceptedAnswer: { "@type": "Answer", text: "Yes — every PrintOpsAI web-to-print store includes automated file preflight at the point of upload. The preflight engine checks every file for correct dimensions with bleed (minimum 3mm), image resolution (minimum 300 DPI), CMYK colour mode, embedded fonts, and correct file format. If a file fails, the customer sees a plain-English error message before they can proceed to checkout. This reduces prepress correction cycles by an average of 50% for our clients." } },
    { "@type": "Question", name: "What integrations does the web-to-print store include?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI web-to-print stores integrate with: Payment — Stripe, PayPal, Klarna, Authorize.net including net-30 trade invoicing; Shipping — FedEx, UPS, USPS, Shippo with live rate calculation; Email — Klaviyo, Mailchimp; CRM — HubSpot, Zoho, Salesforce; Production — PrintOpsAI workflow automation. If you use a tool not listed, we connect most platforms via API." } },
    /* ── Workflow Automation ───────────────────────────────── */
    { "@type": "Question", name: "What is print workflow automation?", acceptedAnswer: { "@type": "Answer", text: "Print workflow automation is the use of software to replace manual handoffs between stages of print production — from order intake through prepress, scheduling, production tracking, and fulfilment. PrintOpsAI's workflow automation covers all 5 stages connected in one continuous pipeline, eliminating manual job ticket creation, email proof cycles, manual press assignment, and manual shipping label creation." } },
    { "@type": "Question", name: "What are the stages of print workflow automation?", acceptedAnswer: { "@type": "Answer", text: "A fully automated print workflow covers 5 core production stages: 1. Order Intake & Routing — orders captured and routed automatically, no manual job ticket creation. 2. Prepress & Preflight — files automatically checked for DPI, bleed, colour mode, fonts; failed files trigger automated correction requests. 3. Production Scheduling — jobs dynamically assigned to optimal press based on capacity and deadline; gang runs identified automatically. 4. Production Tracking — barcode scanning updates job status in real time. 5. Fulfillment & Shipping — labels generated and tracking numbers sent automatically on job completion." } },
    { "@type": "Question", name: "How much manual work does print workflow automation eliminate?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI clients typically reduce manual touch points per job by 40–55% after full workflow automation. Specific savings: order data entry 20–30 minutes per order reduced to 0; preflight checking 10–20 minutes per job automated; manual scheduling 1–2 hours per day automated; shipping label creation 5–10 minutes per job eliminated; customer status call handling 2–3 hours per day CSR time automated. A typical mid-size print shop (10–15 staff) saves 20–30 hours of manual work per week." } },
    { "@type": "Question", name: "How long does print workflow automation take to implement?", acceptedAnswer: { "@type": "Answer", text: "A full PrintOpsAI workflow automation deployment takes 6–12 weeks from audit to full rollout. Weeks 1–2: workflow audit and process mapping. Weeks 3–6: pilot build automating the highest-impact stage first, usually order intake plus prepress. Weeks 7–12: full rollout with remaining stages automated one by one and staff trained. A staged approach means zero disruption to live production. Most clients see measurable ROI within 90 days of full deployment." } },
    { "@type": "Question", name: "What systems does PrintOpsAI workflow automation connect to?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI workflow automation integrates with: Ecommerce — Shopify, WooCommerce; Accounting — QuickBooks; Email/CRM — Klaviyo, HubSpot, Zoho; Production RIP — EFI Fiery, Onyx, Caldera; Shipping — UPS, FedEx, USPS. For shops running legacy MIS systems, we connect via API. We've integrated with over 30 different print-related platforms." } },
    { "@type": "Question", name: "What is the ROI of print workflow automation?", acceptedAnswer: { "@type": "Answer", text: "Most PrintOpsAI clients achieve full return on workflow automation investment within 6–12 months. Key gains: 40–55% reduction in manual labour per job, 20–35% reduction in reprint rate, 96%+ on-time delivery rate, 50% fewer customer status calls. For a print shop doing $2M annually with 12 staff, the total annual value of these gains typically ranges from $80,000–$150,000. We provide a written ROI estimate specific to your shop in your free workflow audit session." } },
    /* ── DevOps ────────────────────────────────────────────── */
    { "@type": "Question", name: "What is DevOps for a print business?", acceptedAnswer: { "@type": "Answer", text: "DevOps for a print business means managing the technology infrastructure that keeps your web store, AI chatbot, workflow automation, and print management systems running reliably 24/7. It covers server management for print file-heavy environments, automated deployment pipelines, 24/7 monitoring, large file handling for 2GB+ print files, backup and disaster recovery, security management, and integration reliability. PrintOpsAI's DevOps service is built specifically for print environments, not adapted from generic IT support." } },
    { "@type": "Question", name: "Why does a web-to-print store need specialised hosting?", acceptedAnswer: { "@type": "Answer", text: "A web-to-print store needs infrastructure significantly more robust than a standard website because print adds file-heavy complexity. Print-specific requirements include: file uploads up to 2GB+ (standard hosting times out at 30–60 seconds), auto-scaling for 5–10x traffic spikes during campaigns, CDN for product images and configurator assets, high-performance database for complex pricing queries, and reliable integration with MIS, ERP, and shipping systems. PrintOpsAI uses AWS infrastructure configured specifically for these requirements." } },
    { "@type": "Question", name: "What does 99.9% uptime mean for a print shop website?", acceptedAnswer: { "@type": "Answer", text: "99.9% uptime means your print shop website is unavailable for less than 9 hours per year. For a shop doing $1M in annual online revenue: 99.9% uptime means roughly $1,000–$2,500 in lost orders per year from downtime; 99.5% uptime means $5,000–$12,500; 99.0% uptime means $10,000–$25,000. Most basic hosting plans offer 99.0–99.5% uptime in practice. PrintOpsAI's infrastructure is built on AWS with load balancing and auto-failover to maintain genuine 99.9% uptime." } },
    { "@type": "Question", name: "Why do large print files fail to upload on our website?", acceptedAnswer: { "@type": "Answer", text: "Large print files fail to upload most commonly because of server timeout configuration. Standard web hosting has a 30–60 second timeout; a 500MB PDF on a 20Mbps connection takes about 200 seconds to upload, so the server closes the connection before the file arrives. Additional causes: PHP max upload size set to 2MB (must be 2GB+), insufficient server memory, and missing chunked upload protocol. PrintOpsAI configures all three: extended timeouts, 2GB+ upload limits, and chunked upload with retry logic." } },
    { "@type": "Question", name: "How should a print shop back up its website and data?", acceptedAnswer: { "@type": "Answer", text: "A print shop should back up four data categories and test restoration quarterly: 1. Database — all orders, customers, products; daily backup with 30-day retention in a geographically separate location. 2. Customer file storage — all uploaded artwork and production files; AWS S3 with versioning. 3. Application code — web store themes, plugins, automation scripts; version control with documented deployment procedures. 4. Environment configuration — server settings, integration credentials, DNS; encrypted backup after every infrastructure change. Most important: test the restoration — a backup never restored is only an assumption. PrintOpsAI tests restoration for every client environment quarterly." } },
    { "@type": "Question", name: "Does my print shop need managed DevOps?", acceptedAnswer: { "@type": "Answer", text: "You probably need managed DevOps if more than 20% of your revenue comes from online orders, you run automated workflows, or your team cannot fix a server issue at 11pm on a Saturday. Signs you need it: your last major system problem took more than 4 hours to resolve; you have B2B clients who depend on always-on portal access; you've had a store crash during a campaign; file uploads fail intermittently. Signs you probably don't need it yet: your website is a brochure with a contact form, technology failures have minimal direct revenue impact, or you have an active in-house developer managing infrastructure. PrintOpsAI's free infrastructure audit will tell you honestly which situation you're in." } },
    /* ── Custom AI ─────────────────────────────────────────── */
    { "@type": "Question", name: "What is custom AI development for a print shop?", acceptedAnswer: { "@type": "Answer", text: "Custom AI development for a print shop means building a bespoke AI system trained on your specific shop's data, workflow, and operational requirements — not a generic SaaS tool adapted for print. Examples include AI pricing engines that quote any job in under 2 seconds, intelligent order routing, computer vision defect detection, predictive inventory management, and custom integration layers. The key difference from SaaS tools: you own the source code permanently with no licensing fees and no vendor dependency." } },
    { "@type": "Question", name: "How much does custom AI development cost for a print shop?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI builds custom AI systems for print shops at a fixed price between $15,000 and $75,000. Typical investment: AI Pricing Engine (single line) $15K–$25K; full catalogue pricing engine $25K–$45K; Intelligent Order Routing $20K–$40K; AI Defect Detection $25K–$50K; Custom Integration Layer (3–5 systems) $15K–$30K; Full AI Operations Platform $50K–$75K. This is a one-time investment with no ongoing licensing fees. A comparable generic AI development company project typically costs $150K–$400K and takes 9–18 months. All projects start with a free scoping call and written fixed-price proposal." } },
    { "@type": "Question", name: "Who owns the code after a custom AI project is complete?", acceptedAnswer: { "@type": "Answer", text: "You own 100% of the source code on completion — this is included with every PrintOpsAI project at no additional cost. On delivery you receive: complete source code in your preferred repository, full technical documentation, API documentation for every integration point, environment configuration files, deployment guides, and staff training documentation. No licensing fees, no vendor dependency — the system runs without paying anyone, including PrintOpsAI, after delivery." } },
    { "@type": "Question", name: "How long does a custom AI project take?", acceptedAnswer: { "@type": "Answer", text: "Most PrintOpsAI custom AI projects are fully deployed in 6–10 weeks from scoping call to launch. Week 1: scoping call and written proposal. Weeks 1–2: project kick-off, data collection, workflow mapping. Weeks 2–4: proof of concept build and accuracy validation. Week 4: client sign-off. Weeks 5–8: full production build and integration testing. Weeks 8–9: staging testing and client review. Weeks 9–10: production deployment and staff training. Week 10+: 30-day post-launch monitoring. We deploy faster because we start from full print industry knowledge, not from a learning curve." } },
    { "@type": "Question", name: "What is the difference between custom AI and using ChatGPT for my print shop?", acceptedAnswer: { "@type": "Answer", text: "ChatGPT and off-the-shelf AI handle generic tasks well. Custom AI handles print-specific operations. ChatGPT cannot give an accurate quote using your price book and machine rates, analyse press output for colour registration errors, or route a job to your optimal press and update your MIS. Those tasks require custom integration with your actual systems and models trained on your specific data. ChatGPT is a general-purpose tool. PrintOpsAI custom AI is an operational system built around your workflow." } },
    { "@type": "Question", name: "Can PrintOpsAI build AI defect detection for a commercial print operation?", acceptedAnswer: { "@type": "Answer", text: "Yes — AI defect detection for commercial print is one of our most-requested custom builds. We collect samples of acceptable and defective output from your specific press, train a computer vision model to recognise defect types (colour shift, registration error, hickeys, streaking, banding), and deploy it into your production workflow via inline inspection or image capture at press delivery. Our models achieve 94–98% accuracy on trained defect types. For packaging printers, we also build AI inventory management with 95%+ stock accuracy and 50–60% reduction in emergency purchases." } },
    /* ── Pricing ───────────────────────────────────────────── */
    { "@type": "Question", name: "How does PrintOpsAI pricing work?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI pricing varies by product. AI Chatbot: monthly subscription based on conversation volume and channels. Web-to-Print Platform: one-time build fee; ongoing Shopify or WooCommerce platform costs are paid directly to those platforms. Workflow Automation: implementation fee plus optional monthly monitoring and support. DevOps Infrastructure: monthly managed service based on infrastructure complexity. Custom AI Development: fixed price per project, $15,000–$75,000, one-time, you own the code. For a specific quote, book a free discovery call." } },
    { "@type": "Question", name: "What is the ROI of using PrintOpsAI?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI clients typically achieve full ROI within 6–12 months. AI Chatbot: 38% more after-hours leads captured; most clients recover the subscription cost within the first week. Web-to-Print: 35–80% more online revenue. Workflow Automation: 40–55% reduction in manual touch-time per job; for a 10-person shop at $20/hour average, $80,000–$120,000 in annual labour savings. Custom AI Pricing Engine: a shop underquoting 5% on $2M revenue recovers $100,000 annually against a one-time $25K–$45K investment. We provide a written ROI estimate in your free discovery session." } },
    { "@type": "Question", name: "Is there a free trial available?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI does not offer a self-serve free trial, but every engagement starts with a free 30-minute demo session that is more valuable than a trial. In the session we show you a live AI chatbot answering quotes for your specific products, demonstrate file preflight catching a real error, walk through workflow automation for your production stage, and show results from a print shop similar to yours. Book a free demo session with no credit card and no commitment required." } },
    { "@type": "Question", name: "How does PrintOpsAI compare in cost to running multiple separate tools?", acceptedAnswer: { "@type": "Answer", text: "Most print shops running disconnected tools spend $10,400–$33,200 per year in software fees alone (web store, print MIS, CRM, email, generic chatbot, accounting) plus $20,000–$40,000 per year in labour for manual data entry between tools — totalling $30,000–$73,000 annually on tools that don't work together. PrintOpsAI connects and replaces most of this stack at a total cost that is often lower than what clients were already spending." } },
    { "@type": "Question", name: "Are there setup fees or long-term contracts?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI's pricing is designed to be low-risk to start. AI Chatbot: no long-term contract; month-to-month after initial setup. Web-to-Print: one-time build fee; no ongoing contract with PrintOpsAI. Workflow Automation: implementation fee plus optional monthly support; no mandatory lock-in. DevOps: monthly managed service with 30-day notice to cancel. Custom AI: fixed price, one-time, no ongoing fees after delivery. We retain clients by producing results, not by locking them in." } },
    { "@type": "Question", name: "What results can I realistically expect from PrintOpsAI?", acceptedAnswer: { "@type": "Answer", text: "Averages across our client base: AI Chatbot — 38% more after-hours leads, 8–14 hours/week CSR time saved. Web-to-Print — 35–80% more online revenue, 20–30% fewer abandoned carts. Workflow Automation — 40–55% reduction in manual touch time, 20–35% fewer reprints, 96%+ on-time delivery. DevOps — 99.9% uptime, 40–60% faster page load times, 95% of issues resolved before users notice. Custom AI — 90-second quote generation, 30–45% fewer reprints, 50–70% fewer manual reviews. In your free demo session we'll give you a realistic expectation for your specific operation." } },
    { "@type": "Question", name: "Can a small print shop afford PrintOpsAI?", acceptedAnswer: { "@type": "Answer", text: "Yes — PrintOpsAI has products for print shops of all sizes. The AI Chatbot is the most accessible starting point; the monthly cost is recovered from a single after-hours lead that would otherwise go to a competitor. For smaller shops (5–15 staff, $500K–$2M revenue), we recommend starting with one product, proving ROI, and adding others as growth funds the investment. For larger operations (15–100+ staff, $2M–$20M revenue), the full platform delivers proportionally larger returns. In your free discovery session we'll tell you honestly whether the investment is viable for your current revenue level." } },
    /* ── Getting Started ───────────────────────────────────── */
    { "@type": "Question", name: "How do I get started with PrintOpsAI?", acceptedAnswer: { "@type": "Answer", text: "The fastest way to get started is to book a free 30-minute demo session. In that session we will understand your specific print operation and current tools, identify your highest-impact automation opportunity, show you a live demonstration relevant to your type of shop, and give you a clear written proposal within 48 hours of the call. There is no commitment required. If you prefer to explore first, our case studies page shows real results from print shops similar to yours." } },
    { "@type": "Question", name: "What information do I need to provide to get started?", acceptedAnswer: { "@type": "Answer", text: "Very little is required to start. For the initial demo session: nothing in advance — just show up with your biggest operational pain point. For the AI Chatbot setup: your price book in any format, product catalogue, standard turnaround times, and FAQs your team answers daily. For Web-to-Print: your product list with specifications, pricing, and brand assets. For Workflow Automation: access to your current workflow for the audit. For Custom AI: a description of the problem you want solved and access to whatever historical data exists." } },
    { "@type": "Question", name: "How quickly can PrintOpsAI be up and running for my print shop?", acceptedAnswer: { "@type": "Answer", text: "Timeline by product: AI Chatbot — 48–72 hours from providing your pricing info to live chatbot on your website; Web-to-Print Store — 2–3 weeks; Workflow Automation — 6–12 weeks for full staged deployment; DevOps — 1–2 weeks for optimisation and monitoring; Custom AI — 6–10 weeks from scoping to full deployment. The AI Chatbot is the fastest-deploying product. Most print shops see their first measurable results within the first week of chatbot deployment." } },
    { "@type": "Question", name: "Will implementing PrintOpsAI disrupt my current print production?", acceptedAnswer: { "@type": "Answer", text: "No — PrintOpsAI is designed to be implemented without disrupting your live production. AI Chatbot: deployed as a widget on top of your existing website — zero disruption. Web-to-Print: built in a staging environment and tested before going live; your existing store keeps running until you choose to switch. Workflow Automation: staged rollout, one process at a time, least disruption risk first. DevOps: infrastructure improvements deployed in maintenance windows with no unplanned downtime. Custom AI: built and tested in staging, deployed to production only after your sign-off." } },
    { "@type": "Question", name: "Do I need any technical knowledge to use PrintOpsAI?", acceptedAnswer: { "@type": "Answer", text: "No technical knowledge is required to use any PrintOpsAI product. AI Chatbot: you review responses in a simple dashboard, no coding. Web-to-Print: standard Shopify or WooCommerce admin interface used by millions of businesses. Workflow Automation: your team uses a production dashboard and barcode scanning. DevOps: completely managed by PrintOpsAI; you receive monthly reports. Custom AI: your team is trained during deployment. PrintOpsAI handles all setup, configuration, integration, and maintenance. Your job is to run your print shop, not to manage technology." } },
    { "@type": "Question", name: "What support do PrintOpsAI clients receive?", acceptedAnswer: { "@type": "Answer", text: "PrintOpsAI clients receive support through a dedicated US-based account lead and a team that understands print operations. Support included with all products: dedicated account lead with monthly results reviews, technical support via email and live chat during US and Canadian business hours, emergency infrastructure support 24/7 for DevOps clients, and monthly performance reports. Product-specific support: AI Chatbot — monthly accuracy review with model updates; Workflow Automation — monthly performance review; Custom AI — 60-day post-launch monitoring included; DevOps — 24/7 monitoring with proactive resolution. You will never talk to someone who doesn't understand print when you contact PrintOpsAI support." } },
  ],
};

const breadcrumbSchema = {
  "@context":  "https://schema.org",
  "@type":     "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home",  item: "https://printai.cloud" },
    { "@type": "ListItem", position: 2, name: "FAQs",  item: "https://printai.cloud/faqs" },
  ],
};

export default function FaqsPage() {
  return (
    <>
      <Script id="ld-breadcrumb-faqs" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      <Script id="ld-faq-faqs"        type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <FaqsPageClient />
    </>
  );
}
